### PR TITLE
Replace images and icons with new logoUpdate

### PR DESCRIPTION
**Pull request by sgraband**
#### What it does

Changed the files and also adjusted the preload.html.

Contributed on behalf of STMicroelectronics

### CODE REVIEW

**Review by planger — COMMENTED** [review]
Thank you very much Simon! I tested it on Ubuntu and it seems to work fine!
Now that I saw it in the application I was wondering though, whether the CDT Cloud Blueprint logo wouldn't look better if instead of white we'd use a color for the font and the cloud, e.g. blue, and made the background transparent. Then it'll probably look better in any theme.

What do you think?

Note that I did something similar here for the website, but kept the foreground color white as it'll be there on a dark background: https://github.com/eclipse-cdt-cloud/website/pull/39/files#diff-28cc6c24e0b1c72feb2ff61a0626a099b24e41c6d150b1f1162dc970131c0577

**Comment by sgraband** [comment]
Sure i can work on this tommorrow. Do you have any objections about the blue used in the Theia blueprint logo?

**Comment by planger** [comment]
Thanks, sounds great!

**Comment by planger** [comment]
@sgraband Please see also https://github.com/eclipse-cdt-cloud/cdt-cloud/pull/34. Thank you!

**Comment by sgraband** [comment]
Made everything transparent and used the new improved version from the other PR.

**Review by planger — APPROVED** [review]
Beautiful! Thank you!

**Comment by planger** [comment]
@sgraband Can you please open a PR against https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint? Thank you!

**Comment by sgraband** [comment]
Done: https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/64

**Comment by planger** [comment]
Merged in https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/64

**Pull request closed without merging**
